general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

animations {
    enabled = false
}

input-field {
    rounding = 0
    outline_thickness = 1
    check_color = rgba(254, 128, 25, 1.0)
    inner_color = rgba(0,0,0,1.0)
    font_color =  rgba(255,255,255,1.0)
}
