# Music Player Daemon configuration
# https://mpd.readthedocs.io/en/stable/user.html#configuration

music_directory    "~/Dropbox/Documents/60-69 Media/62 Music"
playlist_directory "~/.local/share/mpd/playlists"
db_file            "~/.local/share/mpd/database"
state_file         "~/.local/state/mpd/state"
sticker_file       "~/.local/share/mpd/sticker.sql"

bind_to_address "127.0.0.1"
port            "6600"
auto_update     "yes"
restore_paused  "yes"

# Audio Buffering
# This helped get better gapless playback
audio_buffer_size  "8192"
buffer_before_play "10%"

# Send playback through the desktop PipeWire session.
audio_output {
    type "pipewire"
    name "PipeWire"
}
