#:schema https://raw.githubusercontent.com/distinction-dev/alacritty-schema/main/alacritty/reference.json

# import = ["/Users/james/.config/alacritty/gruvbox-black.toml"]
# import = ["/Users/james/.config/alacritty/catppuccin_latte.toml"]
import = ["/Users/james/.config/alacritty/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12
normal.family = "BerkeleyMono Nerd Font"

[keyboard]
bindings = [
  { action = "Copy", key = "C", mods = "Command" },
  { action = "Paste", key = "V", mods = "Command" },
  { action = "Quit", key = "Q", mods = "Command" },
  { action = "Quit", key = "W", mods = "Command" },
  { action = "ResetFontSize", key = "Key0", mods = "Command" },
  { action = "IncreaseFontSize", key = "Equals", mods = "Command" },
  { action = "DecreaseFontSize", key = "Minus", mods = "Command" },
  { action = "SpawnNewInstance", key = "N", mods = "Command" },
  { action = "ToggleFullscreen", key = "F", mods = "Command" },
  { action = "Paste", key = "Paste" },
  { action = "Copy", key = "Copy" },
]

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "Both"
