#!/usr/bin/env sh
set -eu

# Manually load the scripting addition on startup
# This is currently necessary for Big Sur
echo "Loading the scripting addition..."
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

echo "Loading config..."
# yabai -m config layout bsp
yabai -m config layout float
yabai -m config window_shadow float

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
# yabai -m config focus_follows_mouse autoraise

# Set all padding and gaps to 20pt (default: 0)
# yabai -m config top_padding    20
# yabai -m config bottom_padding 20
# yabai -m config left_padding   20
# yabai -m config right_padding  20
# yabai -m config window_gap     20

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

echo "Yabai configuration loaded."
