#!/bin/bash

# Enable a second monitor connected via HDMI
# xrandr --output HDMI1 --auto --left-of eDP1
xrandr --output HDMI1 --auto --pos 0x0 --output eDP1 --auto --pos 1920x312

# Map the touchscreen to stay on the laptop screen
TOUCHSCREEN=`xinput --list --id-only "ELAN Touchscreen"`
xinput --map-to-output $TOUCHSCREEN eDP1

# Fix the wallpaper
sh ~/.fehbg &

notify-send "Second monitor enabled."
