#!/bin/sh

exec j4-dmenu-desktop \
  --term=alacritty \
  --dmenu='bemenu \
    --ignorecase \
    --center \
    --list 10 \
    --margin 1400 \
    --prompt "" \
    --line-height 30 \
    --nb "#21222C" \
    --nf "#F8F8F2" \
    --tb "#21222C" \
    --tf "#F8F8F2" \
    --fb "#21222C" \
    --ff "#F8F8F2" \
    --hb "#F8F8F2" \
    --hf "#21222C" \
    --fn "JetBrains Mono Nerd Font 20px"'
