#!/bin/bash

# This script configures macOS how I like it.
# It's meant to be idempotent so that it can safely be re-run at any time.

set -euo pipefail

pushd ~/.dotfiles

# Install Homebrew
which -s brew || curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

brew update

# Install things distributed as Homebrew packages
export HOMEBREW_NO_ENV_HINTS=true
brew install --quiet \
  bat \
  coreutils \
  cormacrelf/tap/dark-notify \
  docker-compose \
  exa \
  fd \
  fzf \
  gh \
  git \
  highlight \
  htop \
  hub \
  hugo \
  hyperfine \
  koekeishiya/formulae/yabai \
  lua-language-server \
  luarocks \
  markdownlint-cli \
  meetingbar \
  neovim \
  nodenv \
  prettier \
  python \
  rbenv \
  rg \
  shellcheck \
  skhd \
  starship \
  stow \
  stylua \
  tldr \
  tmux \
  tree \
  vale \
  yamllint \
  zsh

# Install some casks
brew install --quiet --cask \
  1password \
  alfred \
  bartender \
  blender \
  cron \
  docker \
  dropbox \
  figma \
  keepingyouawake \
  logseq \
  monitorcontrol \
  notion \
  raycast \
  signal \
  slack \
  spotify \
  tailscale \
  visual-studio-code \
  zoom
#   # Add this back once the cask is > v3.5
#   # iterm2

# Place config files where they belong
stow \
  alfred \
  git \
  hushlogin \
  iterm2 \
  luacheck \
  neovim \
  skhd \
  tmux \
  yabai \
  zsh

# Install some things that are distributed as npm packages
npm install --global \
  @prisma/language-server \
  bash-language-server \
  graphql-language-service-cli \
  yaml-language-server

# Install Oh My ZSH
test -d ~/.oh-my-zsh || sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Enable global key-repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# Enable window dragging by Cmd-ctrl + click'n'drag
# Disable this via `defaults delete -g NSWindowShouldDragOnGesture`
defaults write -g NSWindowShouldDragOnGesture -bool true   

popd

echo 'Finished.'
