#!/bin/bash

# This script configures macOS how I like it.
# It's meant to be idempotent so that it can safely be re-run at any time.

set -euo pipefail

pushd ~/.dotfiles

if [ "$(uname -s)" == "Darwin" ]; then
  # Install Homebrew
  which -s brew || curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

  brew update

  # Install things distributed as Homebrew packages
  export HOMEBREW_NO_ENV_HINTS=true
  brew install --quiet \
    bat \
    coreutils \
    cormacrelf/tap/dark-notify \
    deno\
    exa \
    fd \
    fzf \
    gh \
    git \
    highlight \
    htop \
    hub \
    hugo \
    hyperfine \
    koekeishiya/formulae/yabai \
    lua-language-server \
    luarocks \
    markdownlint-cli \
    mprocs \
    neovim \
    python \
    rbenv \
    rg \
    shellcheck \
    skhd \
    starship \
    stow \
    stylua \
    tldr \
    tmux \
    tmuxinator \
    tree \
    vale \
    volta \
    yamllint \
    zsh

  # Install some casks
  brew install --quiet --cask \
    1password \
    1password-cli \
    arc \
    blender \
    cron \
    dropbox \
    discord \
    figma \
    keepingyouawake \
    linear-linear \
    linearmouse \
    monitorcontrol \
    notion \
    obsidian \
    orbstack \
    raycast \
    signal \
    slack \
    spotify \
    steam \
    tailscale \
    visual-studio-code \
    zoom

  # Enable global key-repeat
  defaults write -g ApplePressAndHoldEnabled -bool false

  # Enable window dragging by Cmd-ctrl + click'n'drag
  # Disable this via `defaults delete -g NSWindowShouldDragOnGesture`
  defaults write -g NSWindowShouldDragOnGesture -bool true
fi

# Place config files where they belong
stow \
  git \
  hushlogin \
  iterm2 \
  kitty \
  luacheck \
  neovim \
  skhd \
  tmux \
  yabai \
  zsh

# Install some things that are distributed as npm packages
# npm install --global \
yarn global add \
  @prisma/language-server \
  @tailwindcss/language-server \
  bash-language-server \
  graphql \
  graphql-language-service-cli \
  typescript \
  typescript-language-server \
  vscode-langservers-extracted \
  yaml-language-server

# Install Oh My ZSH
test -d ~/.oh-my-zsh || sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

popd

echo 'Finished.'
