#!/bin/sh

# change and display the volume level
if [ "$BLOCK_BUTTON" = 5 ];then
	amixer -q set Master 5%+ unmute;
elif [ "$BLOCK_BUTTON" = 4 ];then
	amixer -q set Master 5%- unmute;
fi

VOLUME=$(amixer get Master | grep -E -o -m 1 '[0-9]+%' | tr -d '%')
SYMBOL=

if [ "$VOLUME" -ge "50" ]; then
	SYMBOL=
elif [ "$VOLUME" -eq "0" ]; then
	SYMBOL=
fi

echo "$SYMBOL $VOLUME%"
