#!/bin/sh

# change and display the volume level
case $BLOCK_BUTTON in
	1) amixer -q set Master toggle ;;
	4) amixer -q set Master 5%- unmute ;;
	5) amixer -q set Master 5%+ unmute ;;
esac

VOLUME=$(amixer get Master | grep -E -o -m 1 '[0-9]+%' | tr -d '%')
SYMBOL=

if [ "$VOLUME" -ge "50" ]; then
	SYMBOL=
elif [ "$VOLUME" -eq "0" ]; then
	SYMBOL=
fi

echo "$SYMBOL $VOLUME%"
