# flexoki-light
[colors]
foreground = "#100f0f"
background = "#fffcf0"
cursor_bg = "#100f0f"
cursor_border = "#100f0f"
cursor_fg = "#fffcf0"
selection_bg = "#cecdc3"
selection_fg = "#100f0f"

ansi = ["#100f0f","#af3029","#66800b","#ad8301","#205ea6","#a02f6f","#24837b","#f2f0e5"]
brights = ["#575653","#d14d41","#879a39","#d0a215","#4385be","#ce5d97","#3aa99f","#fffcf0"]
