directory: ~/Music/Music/Media.localized

library: ~/Music/Music/beets-library.db

import:
  move: yes

duplicates:
  delete: yes

match:
  strong_rec_thresh: 0.10

ui:
  color: yes

plugins: fetchart lyrics
